# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

references:
  test_steps: &test_steps
    steps:
      - checkout
      - run:
          name: Install developing package
          command: sudo pip install --upgrade --editable .
      - run:
          name: Setup tests
          command: |
            # install coverage
            sudo pip install --upgrade coverage
      - run:
          name: Run tests
          command: |
            # run unit test cases with coverage
            coverage run -m unittest
            # generate an XML report of coverage results
            coverage xml
            # upload test report to codecov
            bash <(curl -s https://codecov.io/bash)

  deploy_steps: &deploy_steps
    steps:
      - checkout
      - run:
          command: |
            if python setup.py --version | grep -x -P "^\d+(\.\d+)*(\.?(a|b|rc|post)\d+(\.\d+)*)?$" ; then
              sudo pip install --upgrade wheel twine
              python setup.py sdist bdist_wheel
              twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*
            fi

jobs:
  test:
    docker:
      - image: circleci/python
    <<: *test_steps

  deploy:
    docker:
      - image: circleci/python
    <<: *deploy_steps

workflows:
  version: 2
  test-and-deploy: # name of your workflow
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9].+/
            branches:
              ignore: /.*/